# Generated by Django 5.2.6 on 2025-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=2, verbose_name=2),
            preserve_default=False,
        ),
    ]
