# Generated by Django 5.2.6 on 2025-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_authuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
