# Generated by Django 5.2.6 on 2025-09-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_authuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='last_name',
        ),
    ]
